### ISSUE TITLE
Faint Striping/Grid-Lines over Saved Image

### ISSUE THREAD

**Issue by anotherblessed1** [ktgw0316/LightZone#288]
Hi, 

I have used LightZone for years, with no issues. However, as of late, I am encountering a major problem. After saving my work, I noticed that many of my pictures have faint, white sets of grid lines superimposed. They are visible only in the sky. I have tried altering my preferences and settings, to no avail. 

I tried recreating this issue by using a similar set of edits, and it won't always happen. 
The edits I have used in these afflicted pictures are a combination of:

'Zone Mapper'
&
'White Balance'

sometimes supplemented by

'Hue/Saturation'
'Relight'
&/OR
'Sharpen'

Below are some example images where this issue's present:
![IMG_3568_lzn](https://github.com/ktgw0316/LightZone/assets/135561314/4e12916e-7f64-4b87-9025-34782ec4d66b)
![IMG_3680_lzn](https://github.com/ktgw0316/LightZone/assets/135561314/6d37b122-0363-486a-bb49-6a225a518f9b)
![IMG_3683_lzn](https://github.com/ktgw0316/LightZone/assets/135561314/4b1d11c9-708a-428e-9d5f-bb0bf056b62f)

 - Version 4.2.3
 - OS: Windows 11 (64bit)
 
These photos were all shot on an iPhone SE, 2020, with no edits done on the phone. All photo have been at least slightly cropped and rotated in LightZone, in addition to the edits mentioned above.
 
I have seen several threads here on GitHub where this issue was mentioned; some over 10 years old, but none contained a solution. If anyone can help me figure this out, I would be greatly indebted. 

Thank you for your time.
AB1

**Comment by MJacal** [comment]
This has been discussed on the now extinct LightZone forum, I still have samples that I have uploaded in 2017, created with ver. 4.1.7. If I remember correctly, the issue has been fixed at least once.

After that, I haven't noticed this problem for quite a long time, until 2021 and ver. 4.2.1. Now it happens here and there, but I wasn't able to find out, what exactly triggers it.

**Comment by jedd** [comment]
I haven't dived into waybackmachine looking for those earlier discussions (were they public / scraped?) but some troubleshooting questions come to mind - are those grid lines the same distance apart (pixels), or are they a certain number per image (regardless of resolution). 

Have they been seen on anything other than jpg format images?  (I'm assuming apple phones use jpegs, but I'm not an apple user.)

I assume those lines do actually exist in darker areas, just they're only really noticeable in lighter areas (but just in case?).  (Yeah, I could download those images and pixel peep.  : )

**Comment by sfink16** [comment]
> I haven't dived into waybackmachine looking for those earlier discussions (were they public / scraped?) but some troubleshooting questions come to mind - are those grid lines the same distance apart (pixels), or are they a certain number per image (regardless of resolution).
> 
> Have they been seen on anything other than jpg format images? (I'm assuming apple phones use jpegs, but I'm not an apple user.)
> 
> I assume those lines do actually exist in darker areas, just they're only really noticeable in lighter areas (but just in case?). (Yeah, I could download those images and pixel peep. : )

Look at the closed Issues [250](https://github.com/ktgw0316/LightZone/issues/250) and [251](https://github.com/ktgw0316/LightZone/issues/251) to see if that was the subject that was discussed.  [HERE](https://web.archive.org/web/20210609151138/http://lightzoneproject.org/Forum) is the latest Wayback Machine for the old forum that I could find, but I can't find the discussion.

**Comment by jedd** [comment]
Aha, okay, so as per comment from @ktgw0316 on https://github.com/ktgw0316/LightZone/issues/255#issuecomment-1079610223  -- it was thought to be fixed in v4.2.4

I note that @sfink16 is using v4.2.3

**Comment by sfink16** [comment]
> Aha, okay, so as per comment from @ktgw0316 on [#255 (comment)](https://github.com/ktgw0316/LightZone/issues/255#issuecomment-1079610223) -- it was thought to be fixed in v4.2.4
> 
> I note that @sfink16 is using v4.2.3

Correction, Issue [262](https://github.com/ktgw0316/LightZone/issues/262) description shows that I'm using 4.2.4.  I don't know what version I have loaded on my Windows machine, since I don't even have that one turned on at the moment.

**Comment by jedd** [comment]
Oh, really sorry @sfink16  - I looked at this issue above, and mistook it for your issue - but this is actually @anotherblessed1 's report, and mentions 4.2.3.  My mistake.

**Comment by ktgw0316** [comment]
I found the thread on Wayback Machine:
https://web.archive.org/web/20171117164953/http://www.lightzoneproject.org/lorum/faint-white-gridlines

I'll take a deeper look into it and #162 again.

**Comment by ktgw0316** [comment]
I think I found the cause of this issue -- it seems that it is a bug in Java Advanced Imaging library.  I'm going to use a different pixel interpolation method for image upscaling: 2c1c0c8a2f3d4c31e87beb93ffdfd4efc651e5ad.

I wonder why I didn't notice such an easy fix seven years ago...

**Comment by anotherblessed1** [comment]
> 

@ktgw0316 I very highly appreciate your help, as well as everyone else's! I am completely unfamiliar with pixel interpolation in LightZone (although I do understand the concept). Is this something I can change and test, in hopes that the grid lines will be gone?

Also: I am brand new to GitHub, so if I there's anything I can do to be proactive with my issue, please let me know!

**Comment by anotherblessed1** [comment]
> I think I found the cause of this issue -- it seems that it is a bug in Java Advanced Imaging library. I'm going to use a different pixel interpolation method for image upscaling: [2c1c0c8](https://github.com/ktgw0316/LightZone/commit/2c1c0c8a2f3d4c31e87beb93ffdfd4efc651e5ad).
> 
> I wonder why I didn't notice such an easy fix seven years ago...

If you have figured the fix out, could you kindly guide me as to how I can apply it? I have a large batch of photos I really need to finish editing ASAP!

**Comment by ktgw0316** [comment]
@anotherblessed1 OK, I'll upload new installers as soon as possible.

**Comment by ktgw0316** [comment]
@anotherblessed1 I've just uploaded new installers for Windows. Would you test it on your side?
https://github.com/ktgw0316/LightZone/releases/tag/5.0.0beta1

**Comment by MJacal** [comment]
A first impression after a brief test:

For some of my old samples with the "grid-line problem", the issue is fixed by simple resaving as a new version. But not for those, where Tone Mapper was used. (A tool, that I'm not actually using any more.)

After opening any fresh, unedited photo (CR2, NEF), the Tone Mapper immediately creates obvious vertical lines.

(Windows 10, 64-bit)

**Comment by ktgw0316** [comment]
@MJacal Thank you. So there is another bug still in v5.0.0beta1... I'll take a look.

**Comment by anotherblessed1** [comment]
So far, this new version has worked flawlessly. I am able to simply
disable and re-enable the ZoneMapper, and my images are now rendering out
with no grid. You are a lifesaver. Thank you!
